#!/usr/bin/perl
# SCRIPT: rblcheck
# AUTHOR: Peter Elsner <peter.elsner@cpanel.net>
# PURPOSE: Check an IP address against various RBL's (Realtime Blackhole Lists)
# CREATED 8/9/2015
#
use strict;
my $version = "1.0";
use File::stat;
use Net::IP;
use Socket;
use Net::Blacklist::Client;
use Getopt::Long;
use Term::ANSIColor qw(:constants);
$Term::ANSIColor::AUTORESET = 1;
$| = 1;

my @RBLS = qw( 
	0spam.fusionzero.com 
	0spam-killlist.fusionzero.com 
	88.blacklist.zap  
	access.redhawk.org
	admin.bl.kundenserver.de
	all.rbl.jp  
	all.spamblock.unit.liu.se  
	all.spamrats.com  
	any.dnsl.ipquery.org
	aspews.ext.sorbs.net 
	backscatter.spameatingmonkey.net 
	badnets.spameatingmonkey.net  
	b.barracudacentral.org  
	bb.barracudacentral.org 
	blackholes.five-ten-sg.com 
	blackholes.intersil.net
	blackholes.mail-abuse.org
	blacklist.sci.kun.nl 
	blacklist.woody.ch
	bl.blocklist.de
	bl.deadbeef.com
	bl.emailbasura.org
	bl.mailspike.net  
	bl.mipspace.com
	bl.nszones.com 
	block.dnsbl.sorbs.net
	bl.score.senderscore.com
	bl.spamcannibal.org  
	bl.spamcop.net 
	bl.spameatingmonkey.net 
	bl.technovision.dk
	bl.tiopan.com
	bogons.cymru.com  
	bsb.empty.us
	bsb.spamlookup.net
	c10.rbl.hk  
	cbl.abuseat.org 
	cbl.anti-spam.org.cn 
	cblless.anti-spam.org.cn
	cblplus.anti-spam.org.cn
	cdl.anti-spam.org.cn 
	combined.abuse.ch 
	combined.njabl.org
	combined.rbl.msrbl.net
	db.wpbl.info
	dev.null.dk
	dialups.visi.com
	dnsbl-0.uceprotect.net  
	dnsbl-1.uceprotect.net
	dnsbl-2.uceprotect.net
	dnsbl-3.uceprotect.net  
	dnsbl.burnt-tech.com 
	dnsbl.cmbix.com
	dnsbl.cyberlogic.net 
	dnsbl.dronebl.org 
	dnsbl.httpbl.org
	dnsbl.inps.de  
	dnsbl.kempt.net
	dnsbl.mags.net 
	dnsbl.mailshell.net
	dnsbl.mcu.edu.tw  
	dnsbl.proxybl.org
	dnsbl.solid.net
	dnsbl.sorbs.net
	dnsbl.spam-champuru.livedoor.com 
	dnsbl.webequipped.com
	dnsbl.zapbl.net
	dnsbl.zetabl.org
	dnsrbl.swinog.ch  
	drone.abuse.ch 
	dsn.rfc-ignorant.org
	dul.blackhole.cantv.net 
	dul.dnsbl.sorbs.net  
	dyna.spamrats.com 
	dyndns.rbl.jp
	dynip.rothen.com  
	dyn.nszones.com
	escalations.dnsbl.sorbs.net
	exitnodes.tor.dnsbl.sectoor.de
	feb.spamlab.com
	fnrbl.fast.net 
	forbidden.icm.edu.pl 
	fresh.dict.rbl.arix.com 
	fresh.sa_slip.rbl.arix.com 
	fulldom.rfc-ignorant.org
	generic.ixhash.net
	hil.habeas.com 
	hog.blackhole.cantv.net 
	hosteurope.ixhash.net
	httpbl.abuse.ch
	http.dnsbl.sorbs.net 
	images.rbl.msrbl.net 
	intercept.datapacket.net
	ips.backscatterer.org
	ips.barracudacentral.org 
	ix.dnsbl.manitu.net  
	ixhash.junkemailfilter.com
	ixhash.spameatingmonkey.net
	korea.services.net
	l1.bbfh.ext.sorbs.net
	l2.apews.org
	l2.bbfh.ext.sorbs.net
	l3.bbfh.ext.sorbs.net
	l4.bbfh.ext.sorbs.net
	list.bbfh.org  
	list.blogspambl.com  
	list.dsbl.org 
	lookup.dnsbl.iip.lu  
	mail-abuse.blacklist.jippg.org
	misc.dnsbl.sorbs.net 
	multi.surbl.org
	netbl.spameatingmonkey.net 
	new.spam.dnsbl.sorbs.net
	no-more-funn.moensted.dk
	noptr.spamrats.com
	nospam.ant.pl  
	old.spam.dnsbl.sorbs.net
	opm.tornevall.org 
	orvedb.aupads.org 
	problems.dnsbl.sorbs.net
	proxies.dnsbl.sorbs.net 
	psbl.surriel.com  
	rbl2.triumf.ca 
	rbl.abuse.ro
	rbl.choon.net  
	rbl.dns-servicios.com
	rbl.efnethelp.net 
	rbl.efnet.org  
	rbl.efnetrbl.org  
	rbl.interserver.net  
	rbl.megarbl.net
	rbl.msrbl.net  
	rbl.orbitrbl.com  
	rbl.schulte.org
	rbl.softworking.com
	rbl.spamlab.com
	rbl.tdk.net 
	recent.spam.dnsbl.sorbs.net
	relays.bl.kundenserver.de  
	relays.dnsbl.sorbs.net  
	relays.nether.net 
	rhsbl.blackhole.cantv.net  
	rot.blackhole.cantv.net 
	rsbl.aupads.org
	safe.dnsbl.sorbs.net 
	sbl.nszones.com
	schizo-bl.kundenserver.de  
	short.rbl.jp
	smtp.dnsbl.sorbs.net 
	socks.dnsbl.sorbs.net
	spam.abuse.ch  
	spam.blackhole.cantv.net
	spamblock.kundenserver.de  
	spam.dnsbl.sorbs.net
	spamguard.leadmon.net
	spamlist.or.kr 
	spam.pedantic.org 
	spamprobe.drbl.drand.net
	spamrbl.imp.ch 
	spam.rbl.msrbl.net
	spamsources.fabel.dk
	spam.spamrats.com
	spamtrap.drbl.drand.net
	stale.dict.rbl.arix.com 
	stale.sa_slip.arix.com  
	st.technovision.dk
	tor.dan.me.uk  
	tor.dnsbl.sectoor.de 
	tor.efnet.org  
	torexit.dan.me.uk 
	truncate.gbudb.net
	ubl.lashback.com  
	ubl.unsubscore.com
	unsure.nether.net 
	virbl.dnsbl.bit.nl
	virus.rbl.jp
	virus.rbl.msrbl.net  
	vote.drbl.drand.net  
	web.dnsbl.sorbs.net  
	web.rbl.msrbl.net 
	work.drbl.drand.net  
	wormrbl.imp.ch 
	worms-bl.kundenserver.de
	xs.surbl.org
	zen.spamhaus.org  
	z.mailspike.net
	zombie.dnsbl.sorbs.net
);

my $totrbls=@RBLS;
my $mainip; 
my $allips; 
my $email; 
my $checkip; 
my $listedonly;
my $help;
my $enteredip;
my $mainip;
my $ipaddrline;
my $ipaddr;
my @ALIASES;
my @ALL;
my $tocheck;

GetOptions(
	'mainip' => \$mainip,
	'allips' => \$allips,
	'email' => \$email,
	'listedonly' => \$listedonly,
	'checkip' => \$checkip,
	'help' => \$help,
);


if ($mainip) { 
	open(MAINIP,"/var/cpanel/mainip");
	$tocheck = <MAINIP>;
	close(MAINIP);
	&checkit($tocheck);
}

if ($checkip) { 
	$tocheck=@ARGV[0];
	chomp($tocheck);
	&checkit($tocheck);
}


if ($tocheck eq "" and $checkip) { 
	print "Need an IP with the --checkip flag!\n";
	&help;
}

if ($allips) { 
	print "ENTERING ALLIPS CHECK\n";
	open(MAINIP,"/var/cpanel/mainip");
	$mainip = <MAINIP>;
	close(MAINIP);
	push(@ALL,$mainip);
	open(IPALIASES,"/etc/ips");
	@ALIASES=<IPALIASES>;
	close(IPALIASES); 
	foreach $ipaddrline(@ALIASES) { 
		chomp($ipaddrline);
		($ipaddr)=(split(/:/,$ipaddrline))[0];
		push(@ALL,$ipaddr);
	}
	foreach $tocheck(@ALL) { 
		chomp($tocheck);
		&checkit($tocheck);
	}
}

if ($help) { 
	&help;
}

sub checkit() { 
	$enteredip=$_[0];
	my $NUMLISTED=0;
	my $lookuphost;
	if ( $enteredip =~ /:/ and $enteredip !~ /\./ ) {
		my $expandedip = new Net::IP ( $enteredip );
		$lookuphost = join '.', reverse ( split '', $expandedip->ip() );
		$lookuphost =~ s/\.:\././g;
	} 
	elsif ( $enteredip =~ /\./ and $enteredip !~ /:/ ) {
		$lookuphost = join '.', reverse ( split /\./, $enteredip );
	} 
	else {
		die "FATAL - invalid host \"$enteredip\"\n";
	}
	foreach my $blacklist (@RBLS) {
		if ($listedonly) {
			print ".";
		}
		print "Checking List: " . YELLOW . $blacklist . WHITE . ": $enteredip is " unless($listedonly);
		my $lookup = "$lookuphost.$blacklist";
		my $result = gethostbyname ( $lookup );
		if ( ! defined $result ) { 
			print GREEN "[NOT LISTED]\n" unless($listedonly);
		}
		else { 
			$result = inet_ntoa ( $result );
			if ($listedonly) { 
				print "\n\nList: " . YELLOW . $blacklist . WHITE . ": $enteredip is ";
				print RED "[LISTED] ($result)\n\n";
			}
			else { 
				print RED "[LISTED] ($result)\n";
			}
			$NUMLISTED++;
		}
	}

	print "\n";
	print "Checked $totrbls Realtime Blackhole Lists (RBL's) & found $enteredip listed in $NUMLISTED of them.\n";
}

exit;

sub help { 
	print "Usage information goes here!\n";
	exit;
}
